name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: macos-latest
            libcxx: libc++
          - os: ubuntu-latest
            libcxx: libstdc++11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v1

      - name: Install conan and conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools

      - uses: actions/checkout@v2

      - name: conan
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          mkdir ${{github.workspace}}/build -force
          cd ${{github.workspace}}/build
          conan install ${{github.workspace}} -s build_type=${{ env.BUILD_TYPE }} --build missing

      - name: conan
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          mkdir -p ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          conan install ${{github.workspace}} -s compiler.libcxx=${{ matrix.libcxx }} -s build_type=${{ env.BUILD_TYPE }} --build missing

      - name: CMake configure
        if: ${{ contains(matrix.os, 'windows') }}
        run:
          cmake -B ${{github.workspace}}/build

      - name: CMake configure
        if: ${{ !contains(matrix.os, 'windows') }}
        run:
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: build
        run:
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: test
        working-directory: ${{github.workspace}}/build
        run:
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
